name: Node CI helper
description: >
  Sets up Node.js, installs dependencies, and runs a custom script with npm cache enabled.

inputs:
  script:
    description: The npm command or script to execute once dependencies are installed.
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
        cache: npm

    - name: Install dependencies
      run: npm ci
      working-directory: .

    - name: Run script
      run: ${{ inputs.script }}
      working-directory: ,
